### ISSUE TITLE
[Feature] 用4卡跑ds-r1，每个卡只用可4GB左右，可以怎么设置yaml让单卡的显存使用率提升

### ISSUE THREAD

**Issue by PhzCode** [kvcache-ai/ktransformers#1232]
### Checklist

- [x] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/kvcache-ai/ktransformers/discussions. Otherwise, it will be closed.
- [x] 2. To help the community, I will use Chinese/English or attach an Chinese/English translation if using another language. Non-English/Chinese content without translation may be closed.

### Motivation

我使用仓库的`DeepSeek-V3-Chat-multi-gpu-4.yaml`运行了4卡的deepseek-r1，每个卡只用了4GB左右，但是H20单卡有90GB，可以把部分的逻辑搬移到gpu做吗，现在推理比较慢。可以怎么修改yaml呢？
另外，我把yaml的model.embed_tokens部分改为这样后，会报错cuda和cpu两个设备的错误，model.embed_tokens在代码里默认使用cpu了吗？
```
- match:
    name: "^model.embed_tokens"
  replace:
    class: "default"
    kwargs:
      generate_device: "cuda:0"
      prefill_device: "cuda:0"
```
