### ISSUE TITLE
[Bug] 使用V0.3版本开启AMX后运行会卡死

### ISSUE THREAD

**Issue by mequanwei** [kvcache-ai/ktransformers#1282]
### 检查清单

- [x] 1. 我已经搜索过相关问题，但未能获得预期的帮助
- [x] 2. 该问题在最新版本中尚未修复
- [x] 3. 请注意，如果您提交的BUG相关 issue 缺少对应环境信息和最小可复现示例，我们将难以复现和定位问题，降低获得反馈的可能性
- [x] 4. 如果您提出的不是bug而是问题，请在讨论区发起讨论 https://github.com/kvcache-ai/ktransformers/discussions。否则该 issue 将被关闭
- [x] 5. 为方便社区交流，我将使用中文/英文或附上中文/英文翻译（如使用其他语言）。未附带翻译的非中文/英语内容可能会被关闭

### 问题描述

1.使用V0.3版本运行Deepseek-V3,可以成功对话。
2.使用同样的代码，开启amx. 修改gguf_path为bf16，以及修改optimize_rules为DeepSeek-V3-Chat-amx.yaml 运行报错。怀疑是optimize_rules未适配。
3. 尝试修改optimize_rules。使用 DeepSeek-V3-Chat-serve.yaml 为模板，修改 experts 部分后，运行后可以成功加载模型，但是进行warmup 时会卡住。

### 复现步骤

1.使用V0.3版本运行Deepseek-V3,可以成功对话。
```
python ktransformers/server/main.py --port 10002 --model_path /data/DeepSeek-V3-0324-Q4_K_M/ --gguf_path /data/DeepSeek-V3-0324-Q4_K_M_gguf/ --optimize_config_path ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-serve.yaml --max_new_tokens 1024  --backend_type balance_serve 
```
2.使用同样的代码，开启amx. 修改gguf_path为bf16，以及修改optimize_rules为DeepSeek-V3-Chat-amx.yaml
```
python ktransformers/server/main.py --port 10002 --model_path /data/DeepSeek-V3-0324-Q4_K_M/ --gguf_path /data/DeepSeek-V3-0324-BF16/ --optimize_config_path ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-amx.yaml --max_new_tokens 1024  --backend_type balance_serve 
```
运行报错
```
DeepseekV3RMSNorm.forward() takes 2 positional arguments but 4 were given
```
3. 尝试修改optimize_rules。使用 DeepSeek-V3-Chat-serve.yaml 为模板，修改 experts 部分，增加 backend:"AMXInt8"
```
- match:
    name: "^model\\.layers\\..*\\.mlp\\.experts$"
  replace:
    class: ktransformers.operators.experts.KTransformersExpertsV2     # custom MoE Kernel with expert paralleism
    kwargs:
      prefill_device: "cuda"
      prefill_op: "KExpertsTorch"
      generate_device: "cpu"
      generate_op: "KExpertsCPU"
      out_device: "cuda"
      backend: "AMXInt8" # or "AMXBF16" or "llamafile" (default)
  recursive: False # don't recursively inject submodules of this module
```
运行后可以成功加载模型，但是进行warmup 时会卡住。
```
loading blk.60.ffn_norm.weight to cuda
loading output_norm.weight to cuda
Getting inference context from sched_client.
sched_rpc started with PID: 2096819
Got inference context, sending it to subscribers.
Rebuilding kvcache
kv_cache loaded successfully.
capturing cuda graph 1 1
2025-05-12 16:01:27,264 - INFO - flashinfer.jit: Loading JIT ops: batch_mla_attention_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_ckv_512_head_dim_kpe_64_profiler_False
/home/moffett/miniconda3/envs/ktransformers/lib/python3.11/site-packages/torch/utils/cpp_extension.py:2059: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/moffett/miniconda3/envs/ktransformers/lib/python3.11/site-packages/torch/utils/cpp_extension.py:2059: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
2025-05-12 16:01:50,689 - INFO - flashinfer.jit: Finished loading JIT ops: batch_mla_attention_dtype_q_bf16_dtype_kv_bf16_dtype_o_bf16_dtype_idx_i32_head_dim_ckv_512_head_dim_kpe_64_profiler_False
2025-05-12 16:01:50,775 - INFO - flashinfer.jit: Loading JIT ops: norm
/home/moffett/miniconda3/envs/ktransformers/lib/python3.11/site-packages/torch/utils/cpp_extension.py:2059: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/moffett/miniconda3/envs/ktransformers/lib/python3.11/site-packages/torch/utils/cpp_extension.py:2059: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
2025-05-12 16:02:06,773 - INFO - flashinfer.jit: Finished loading JIT ops: norm
```

### 环境信息

CPU: Intel (R) Xeon (R) Gold 6454S 1T DRAM (2 NUMA nodes)
GPU: 4090D 24G VRAM
