### ISSUE TITLE
请问这俩配置文件是不是有点问题？

### ISSUE THREAD

**Issue by adamhj** [kvcache-ai/ktransformers#1325]
https://github.com/kvcache-ai/ktransformers/blob/main/ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-multi-gpu-4.yaml
https://github.com/kvcache-ai/ktransformers/blob/main/ktransformers/optimize/optimize_rules/DeepSeek-V3-Chat-multi-gpu-8.yaml

这俩多GPU配置文件里，匹配layers的正则似乎只写到60层，比如8卡的这段：
```
# GPU 7: layers 56–60
- match:
    name: "^model\\.layers\\.(5[6-9]|60)\\."
    class: ktransformers.models.modeling_deepseek_v3.DeepseekV3RotaryEmbedding
  replace:
    class: ktransformers.operators.RoPE.YarnRotaryEmbeddingV3
    kwargs:
      generate_device: "cuda:7"
      prefill_device: "cuda:7"
```

但是我看hf上的deepseek-v3模型(无论是老的还是0324)是有layers.61的，所以想问下看这俩配置文件是不是少了一层？
