### ISSUE TITLE
docker container fails to start due to missing package 'uvicorn'

### ISSUE THREAD

**Issue by sammcj** [kvcache-ai/ktransformers#66]
Using the latest official Dockerfile ktransformers crashes on start due to a missing package:

```
docker logs -f ktransformers

Traceback (most recent call last):
  File "/opt/conda/bin/ktransformers", line 5, in <module>
    from ktransformers.server.main import main
  File "/opt/conda/lib/python3.10/site-packages/ktransformers/server/main.py", line 5, in <module>
    import uvicorn.logging
ModuleNotFoundError: No module named 'uvicorn'
```

---

compose for reference

```
...
services:
  &name ktransformers:
    <<: [*ai-common, *restart, *secopts, *autoupdate, *gpu]
    container_name: *name
    hostname: *name
    profiles:
      - *name
    build:
      context: https://github.com/kvcache-ai/ktransformers.git#main
      dockerfile: Dockerfile
    ports:
      - 10002/tcp
    volumes:
      - /mnt/llm/models:/models
      - ./ktransformers:/config/
    command:
      - "ktransformers"
      - "serve"
      - "--port"
      - "10002"
      - "--gguf_path"
      - "/models/deepseek-coder-v2-instruct/DeepSeek-Coder-V2-Instruct-Q4_K_M.gguf"
      - "--web True"
      - "--optimize_rule_path"
      - "/config/deepseek-coder-v2-3gpu.yaml"
    networks:
      - traefik-servicenet
    labels:
      traefik.enable: true
      org.hotio.pullio.update: true
      traefik.http.routers.ktransformers.rule: Host(`ktransformers.my.internal.domain`)
      traefik.http.routers.ktransformers.tls.certresolver: le
      traefik.http.routers.ktransformers.entrypoints: websecure
      traefik.http.routers.ktransformers.tls.domains[0].main: "*.my.internal.domain"
      traefik.http.routers.ktransformers.service: ktransformers-service
      traefik.http.services.ktransformers-service.loadbalancer.server.port: 10002
      traefik.http.routers.ktransformers.middlewares: authentik
```
